apiVersion: v1
kind: ServiceAccount
metadata:
  name: uptime-kuma-controller-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uptime-kuma-controller-cr
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: uptime-kuma-controller-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: uptime-kuma-controller-cr
subjects:
- kind: ServiceAccount
  name: uptime-kuma-controller-sa
  namespace: lan
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptime-kuma-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma-controller
  template:
    metadata:
      labels:
        app: uptime-kuma-controller
    spec:
      serviceAccountName: uptime-kuma-controller-sa
      containers:
      - name: uptime-kuma-controller
        image: thearyadev0/uptime-kuma-controller:1.0.1
        # command: ["sleep", "infinity"]
        imagePullPolicy: Always
        env:
          - name: CONTROLLER_TAG
            value: k8s-ingress
          - name: UPTIME_KUMA_API_URL
            value: http://uptime-kuma-service:3001
          - name: KUMA_PASSWORD
            value: Arrk1174
          - name: KUMA_USERNAME
            value: arya
      restartPolicy: Always
